on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
name: Build and publish to DockerHub
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_REPOSITORY: 'keepassxc'
jobs:
  stable:
    name: stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Build and Publish stable to DockerHub
        run: |
          export DOCKER_BUILD_CONTEXT="stable"
          export LATEST_RELEASE=`curl --silent "https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest" | jq .tag_name | xargs`
          export DOCKER_IMAGE_VERSION=${LATEST_RELEASE}
          export DOCKER_TAGS="stable,latest,${DOCKER_IMAGE_VERSION}"
          ./scripts/publish.sh
  edge:
    name: edge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Build and Publish edge to DockerHub
        run: |
          export DOCKER_BUILD_CONTEXT="edge"
          export DOCKER_IMAGE_VERSION="master"
          export DATE_TAG=`date --utc --rfc-3339=date`
          export DOCKER_TAGS="edge,edge-${DATE_TAG}"
          ./scripts/publish.sh

