on: 
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '10 5 * * TUE'
name: Build and publish to DockerHub
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - 
        name: Update Dockerfiles
        run: |
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            ./scripts/update.sh
            git push
  stable:
    needs: update
    name: stable
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
        with:
          cache-image: false
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      - 
        name: Build and Publish stable docker images
        run: |
            export DOCKER_BUILD_CONTEXT="stable"
            export DOCKER_IMAGE_VERSION=`sed -ne "s/^ARG KEEPASSXC_VERSION=['\"]\([^'\"]*\)['\"]/\1/p" stable/Dockerfile`
            export DOCKER_TAGS="stable,latest,${DOCKER_IMAGE_VERSION}"
            ./scripts/publish.sh
  edge:
    needs: update
    name: edge
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
        with:
          cache-image: false
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      - 
        name: Build and Publish edge docker images
        run: |
            export DOCKER_BUILD_CONTEXT="edge"
            export DOCKER_IMAGE_VERSION="edge"
            export DOCKER_TAGS="edge"
            ./scripts/publish.sh

