on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
name: Build and publish to DockerHub
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_REPOSITORY: 'keepassxc'
jobs:
  stable:
    name: stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish stable to DockerHub
        run: |
          BASE_NAME="${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${DOCKER_REPOSITORY}"
          SOURCE_LABEL="org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}"
          REVISION_LABEL="org.opencontainers.image.revision=${GITHUB_SHA}"
          CREATED_LABEL="org.opencontainers.image.created=`date --utc --rfc-3339=seconds`"
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin "${DOCKER_REGISTRY}"
          docker build --tag "${BASE_NAME}:stable" --label "${SOURCE_LABEL}" --label "${REVISION_LABEL}" --label "${CREATED_LABEL}" stable
          docker tag "${BASE_NAME}:stable" "${BASE_NAME}:stable-`date --utc --rfc-3339=date`"
          docker tag "${BASE_NAME}:stable" "${BASE_NAME}:`docker inspect ${BASE_NAME}:stable | jq -r .[0].ContainerConfig.Labels.version`"
          docker tag "${BASE_NAME}:stable" "${BASE_NAME}:latest"
          docker push "${BASE_NAME}"
          docker logout
  edge:
    name: edge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish edge to DockerHub
        run: |
          BASE_NAME="${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${DOCKER_REPOSITORY}"
          SOURCE_LABEL="org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}"
          REVISION_LABEL="org.opencontainers.image.revision=${GITHUB_SHA}"
          CREATED_LABEL="org.opencontainers.image.created=`date --utc --rfc-3339=seconds`"
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY}
          docker build --tag "${BASE_NAME}:edge" --label "${SOURCE_LABEL}" --label "${REVISION_LABEL}" --label "${CREATED_LABEL}" edge
          docker tag "${BASE_NAME}:edge" "${BASE_NAME}:edge-`date --utc --rfc-3339=date`"
          docker push "${BASE_NAME}"
          docker logout

