on: push
name: Build and deploy on push
jobs:
  docker_build_stable:
    name: Docker Build stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build
      uses: actions/docker/cli@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: build -t "${DOCKER_USERNAME}/keepassxc:latest" stable
    - name: Docker Tag
      uses: actions/docker/tag@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: ${DOCKER_USERNAME}/keepassxc ${DOCKER_USERNAME}/keepassxc --no-ref --no-sha 
    - name: Login DockerHub
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Push
      uses: actions/docker/cli@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: push "${DOCKER_USERNAME}/keepassxc"
  docker_build_master:
    name: Docker Build master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build
      uses: actions/docker/cli@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: build -t "${DOCKER_USERNAME}/keepassxc:master" master
    - name: Login DockerHub
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Push
      uses: actions/docker/cli@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: push "${DOCKER_USERNAME}/keepassxc"

