on:
  schedule:
  - cron: '0 1 * * *'
name: Build and deploy on push
jobs:
  dockerhub_publish_stable:
    name: DockerHub Build and Publish stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish stable to DockerHub
      uses: westonsteimel/action-docker-publish@master
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'keepassxc'
        build_context: 'stable'
        dockerfile_path: 'stable/Dockerfile'
        tag_ref: false
        tag_latest: true
        tag_version: true
        tag_sha: false
        tag_timestamp: false
  dockerhub_publish_master:
    name: DockerHub Build and Publish master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish master to DockerHub
      uses: westonsteimel/action-docker-publish@master
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'keepassxc'
        build_context: 'master'
        dockerfile_path: 'master/Dockerfile'
        tag_ref: true
        tag_latest: false
        tag_version: false
        tag_sha: false
        tag_timestamp: true

